name: Build and Download .exe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release

    - name: Get current date (Windows)
      shell: pwsh
      run: echo "date=$((Get-Date).ToString('yyyy-MM-dd'))" >> $env:GITHUB_ENV

    - name: Move executable to root directory
      run: mv build/Release/rowmerge.exe rowmerge.exe

    - name: Upload rowmerge executable and data
      uses: actions/upload-artifact@v4
      with:
        name: rowmerge-${{ env.date }}
        path: |
          rowmerge.exe
          data/
  

