name: Publish the executables and datasets on multiple platforms

on:
  workflow_dispatch:
  push:
    tags:
      - "*"
permissions:
  contents: write
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        include:
          - os: windows-latest
            cpp_compiler: cl
            artifact_name: rowmerge.exe
            asset_name: rowmerge-windows
          - os: ubuntu-latest
            cpp_compiler: g++
            artifact_name: rowmerge
            asset_name: rowmerge-linux
          - os: macos-latest
            cpp_compiler: clang++
            artifact_name: rowmerge
            asset_name: rowmerge-macos-amd64

    steps:
      - uses: actions/checkout@v4

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/Release/${{ matrix.artifact_name }}
            docs/*.md
            LICENSE
            data/*.txt
